server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.0.0.135:3306/babytun?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  redis:
    host: 10.0.0.135
    port: 6379
    database: 2
  kafka:
    bootstrap-servers: 10.0.0.135:9092
    consumer:
      group-id: my-group
      # 手动ACK，需要你在代码中调用 acknowledgment.acknowledge()
      enable-auto-commit: false
      # 单次 poll 拉取消息数量，相当于 RabbitMQ prefetch = 10
      max-poll-records: 10
      # 自动转换消息
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    listener:
      # 配置 Kafka Listener 使用手动 ack
      ack-mode: manual # 或 manual_immediate
  #rabbitmq:
  #  host: 10.0.0.135
  #  port: 5672
  #  username: guest
  #  password: guest
  #  virtual-host: /
  #  listener:
  #    simple:
  #      #定义消费者做多同时处理10个消息
  #      prefetch: 10
  #      #消息手动确认
  #      acknowledge-mode: manual
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
