spring:
  ai:
    openai:
      api-key: proj_TwoXAxweOI4HqnVS5KtZBHdP    # ✅ 这里填你的 OpenAI Key
      base-url: https://api.openai.com/v1             # ✅ 可选，一般默认即可
  datasource:
    url: jdbc:postgresql://10.0.0.135:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true         # 控制台显示 SQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect   # ✅ 手动指定方言，防止自动识别失败
        format_sql: true    # SQL 格式化
  session:
    store-type: jdbc
  sql:
    init:
      mode: never
      schema-locations: classpath:org/springframework/session/jdbc/schema-postgresql.sql
springdoc:
  swagger-ui:
    path: /swagger-ui.html

